/**
 * Model Orchestrator Service
 *
 * Core orchestration logic that:
 *  1. Analyzes incoming queries using QueryAnalyzerService
 *  2. Selects primary + secondary models via ModelRegistryRepository
 *  3. Invokes model providers and builds ModelResults
 *  4. Combines outputs with EnsembleCombinerService
 *  5. Falls back to general-purpose model with degradation notice (Req 1.5)
 *  6. Logs every selection decision for audit/explainability (Req 1.8)
 *
 * Requirements: 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8
 */

import { Injectable, Logger } from '@nestjs/common';

import { QueryAnalyzerService } from './query-analyzer/query-analyzer.service';
import { ModelRegistryRepository } from './model-registry/model-registry.repository';
import { EnsembleCombinerService } from './ensemble/ensemble-combiner.service';

import { Query, ModelCapability } from './interfaces/query.interface';
import {
  ModelRouting,
  ModelResults,
  ModelOutput,
  ModelDecision,
  UnifiedResult,
  EnsembleStrategy,
} from './interfaces/model.interface';
import { IModelProvider } from './interfaces/model-provider.interface';

export interface OrchestratorResult extends UnifiedResult {
  degraded: boolean;
  degradationReason?: string;
  routing: ModelRouting;
}

/**
 * Fallback notice added to the answer when the primary model was unavailable
 * and we fell back to the general-purpose model (Requirement 1.5).
 */
const DEGRADATION_NOTICE =
  '[Degraded mode – primary model unavailable. Response generated by general-purpose fallback.]';

@Injectable()
export class OrchestratorService {
  private readonly logger = new Logger(OrchestratorService.name);

  /**
   * Runtime model provider registry — supports pluggable architecture (Req 1.6).
   * Providers are registered by OrchestratorModule or dynamically at runtime.
   */
  private readonly providers = new Map<string, IModelProvider>();

  constructor(
    private readonly queryAnalyzer: QueryAnalyzerService,
    private readonly modelRegistry: ModelRegistryRepository,
    private readonly ensembleCombiner: EnsembleCombinerService,
  ) {}

  // ─── Provider Management (Req 1.6 — pluggable) ──────────────────────────────

  /**
   * Register a model provider.  Can be called at any time without restarting
   * the service, fulfilling the pluggable architecture requirement.
   */
  registerProvider(provider: IModelProvider): void {
    this.providers.set(provider.modelId, provider);
    this.logger.log(`Provider registered: ${provider.modelId} (${provider.displayName})`);
  }

  /**
   * Unregister a provider (e.g., when an upstream API is decommissioned).
   */
  unregisterProvider(modelId: string): void {
    this.providers.delete(modelId);
    this.modelRegistry.updateStatus(modelId, 'unavailable');
    this.logger.log(`Provider unregistered: ${modelId}`);
  }

  // ─── Main orchestration entry point ─────────────────────────────────────────

  /**
   * Route a query to the appropriate model(s), execute, combine, and return
   * a unified result with full audit trail.
   */
  async process(query: Query): Promise<OrchestratorResult> {
    this.logger.log(`Processing query: ${query.id}`);

    // 1. Classify the query
    const classification = await this.queryAnalyzer.analyzeQuery(query);
    this.logger.log(
      `Query ${query.id} classified as '${classification.type}' (conf=${classification.confidence})`,
    );

    // 2. Build routing plan
    const routing = this.buildRouting(classification.requiredCapabilities);
    this.logger.log(
      `Routing: primary=${routing.primaryModel.id}, strategy=${routing.ensembleStrategy}`,
    );

    // 3. Execute models and collect outputs
    const { results, degraded, degradationReason } = await this.executeModels(
      query,
      routing,
    );

    // 4. Combine results
    const modelAccuracies = this.buildAccuraciesMap(results);
    const unified = this.ensembleCombiner.combine(results, routing.ensembleStrategy, modelAccuracies);

    // 5. Append degradation notice if we fell back (Req 1.5)
    if (degraded) {
      unified.answer = degraded
        ? `${unified.answer}\n\n${DEGRADATION_NOTICE}`
        : unified.answer;
    }

    // 6. Log decisions for audit (Req 1.8)
    this.logDecisions(query.id, routing, unified.modelDecisions);

    return {
      ...unified,
      degraded,
      degradationReason,
      routing,
    };
  }

  // ─── Routing ─────────────────────────────────────────────────────────────────

  /**
   * Select primary, secondary, and fallback models based on registry performance.
   * Requirements: 1.2 (route to appropriate model), 1.4 (use performance metrics)
   */
  private buildRouting(capabilities: ModelCapability[]): ModelRouting {
    const fallbackMeta = this.modelRegistry.findFallback();
    const fallbackRef = fallbackMeta
      ? { id: fallbackMeta.id, name: fallbackMeta.name, type: fallbackMeta.type, version: fallbackMeta.version, capabilities: fallbackMeta.capabilities }
      : { id: 'general-fallback', name: 'General Fallback', type: 'general', version: '1.0.0', capabilities: capabilities };

    // Primary: best model for the first (highest-priority) required capability
    const primaryCapability = capabilities[0];
    const primaryMeta = primaryCapability
      ? this.modelRegistry.findBestForCapability(primaryCapability)
      : undefined;

    const primaryRef = primaryMeta
      ? { id: primaryMeta.id, name: primaryMeta.name, type: primaryMeta.type, version: primaryMeta.version, capabilities: primaryMeta.capabilities }
      : fallbackRef;

    // Secondary: best models for remaining capabilities (avoid duplication)
    const secondaryRefs = capabilities
      .slice(1)
      .map((cap) => this.modelRegistry.findBestForCapability(cap))
      .filter((m): m is NonNullable<typeof m> => !!m && m.id !== primaryRef.id)
      .map((m) => ({ id: m.id, name: m.name, type: m.type, version: m.version, capabilities: m.capabilities }));

    // Remove duplicate secondary models
    const seen = new Set<string>([primaryRef.id]);
    const uniqueSecondary = secondaryRefs.filter((r) => {
      if (seen.has(r.id)) return false;
      seen.add(r.id);
      return true;
    });

    // Choose ensemble strategy based on number of models involved
    const ensembleStrategy: EnsembleStrategy =
      uniqueSecondary.length === 0 ? 'cascade' : 'weighted_vote';

    return {
      primaryModel: primaryRef,
      secondaryModels: uniqueSecondary,
      fallbackModel: fallbackRef,
      ensembleStrategy,
    };
  }

  // ─── Model execution ─────────────────────────────────────────────────────────

  /**
   * Invoke the primary model (and secondary models in parallel), falling back
   * to the general-purpose model if the primary is unavailable (Req 1.5).
   */
  private async executeModels(
    query: Query,
    routing: ModelRouting,
  ): Promise<{
    results: ModelResults;
    degraded: boolean;
    degradationReason?: string;
  }> {
    const allModelIds = [
      routing.primaryModel.id,
      ...routing.secondaryModels.map((m) => m.id),
    ];

    // Try to invoke all selected models in parallel
    const invocationPromises = allModelIds.map((modelId) =>
      this.invokeProvider(query, modelId),
    );

    const outcomes = await Promise.allSettled(invocationPromises);

    const outputs: ModelOutput[] = [];
    let degraded = false;
    let degradationReason: string | undefined;

    outcomes.forEach((outcome, idx) => {
      if (outcome.status === 'fulfilled' && outcome.value) {
        outputs.push(outcome.value);
      } else {
        const failedId = allModelIds[idx];
        this.logger.warn(`Model ${failedId} failed: ${(outcome as PromiseRejectedResult).reason}`);
        if (failedId === routing.primaryModel.id) {
          degraded = true;
          degradationReason = `Primary model '${failedId}' unavailable`;
        }
      }
    });

    // If primary failed, invoke the fallback model (Req 1.5)
    if (degraded) {
      this.logger.warn(`Falling back to: ${routing.fallbackModel.id}`);
      const fallbackOutput = await this.invokeProvider(query, routing.fallbackModel.id);
      if (fallbackOutput) {
        outputs.push(fallbackOutput);
      }
    }

    // If we still have nothing, synthesise an empty output
    if (outputs.length === 0) {
      outputs.push({
        modelId: 'none',
        result: 'No models available to process this query.',
        confidence: 0,
        latency: 0,
      });
      degraded = true;
      degradationReason = 'All models unavailable';
    }

    // Build ModelResults maps
    const results: ModelResults = {
      results: new Map(outputs.map((o) => [o.modelId, o])),
      latencies: new Map(outputs.map((o) => [o.modelId, o.latency])),
      confidences: new Map(outputs.map((o) => [o.modelId, o.confidence])),
    };

    return { results, degraded, degradationReason };
  }

  /**
   * Invoke a single provider by its model ID.
   * Returns undefined if the provider is not registered or unavailable.
   */
  private async invokeProvider(
    query: Query,
    modelId: string,
  ): Promise<ModelOutput | undefined> {
    const provider = this.providers.get(modelId);

    if (!provider) {
      // No runtime provider registered; fall back to registry-based stub answer
      const meta = this.modelRegistry.findById(modelId);
      if (!meta || meta.status !== 'available') return undefined;

      this.logger.debug(`No runtime provider for ${modelId}; using stub response`);
      const start = Date.now();
      this.modelRegistry.recordCall(modelId, { success: true, latencyMs: 1 });
      return {
        modelId,
        result: `[Stub] No live provider registered for model '${modelId}'.`,
        confidence: meta.metrics.accuracy * 0.8,
        latency: Date.now() - start,
        metadata: { stub: true },
      };
    }

    // Check availability before invoking
    if (!provider.isAvailable()) {
      this.modelRegistry.updateStatus(modelId, 'unavailable');
      return undefined;
    }

    const start = Date.now();
    try {
      const providerOutput = await provider.invoke({
        queryId: query.id,
        content: query.content,
        context: query.context as unknown as Record<string, unknown>,
        parameters: {},
      });

      const latencyMs = Date.now() - start;
      this.modelRegistry.recordCall(modelId, { success: true, latencyMs, cost: providerOutput.costUsd });

      return {
        modelId,
        result: providerOutput.result,
        confidence: providerOutput.confidence,
        latency: latencyMs,
        metadata: providerOutput.metadata,
      };
    } catch (err) {
      const latencyMs = Date.now() - start;
      this.modelRegistry.recordCall(modelId, { success: false, latencyMs });
      this.logger.error(`Provider ${modelId} threw: ${(err as Error).message}`);
      throw err;
    }
  }

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  /** Build model-accuracy map from registry for the ensemble combiner */
  private buildAccuraciesMap(results: ModelResults): Map<string, number> {
    const acc = new Map<string, number>();
    for (const modelId of results.results.keys()) {
      const metrics = this.modelRegistry.getMetrics(modelId);
      acc.set(modelId, metrics?.accuracy ?? 0.75);
    }
    return acc;
  }

  /** Persist model-selection decisions for audit (Req 1.8) */
  private logDecisions(
    queryId: string,
    routing: ModelRouting,
    decisions: ModelDecision[],
  ): void {
    this.logger.log(
      `[AUDIT] Query=${queryId} primary=${routing.primaryModel.id} ` +
        `strategy=${routing.ensembleStrategy} decisions=${decisions.length}`,
    );
  }
}
