'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  askEllineaApi, assignPlatformOrgPackage, createPlatformOrg, createPlatformOrgUser,
  createPlatformPackage, fetchHealth, fetchPlatformOrgDateTimeSettings,
  fetchPlatformMetrics, fetchPlatformHealthSummary, fetchPlatformOrgPackage, fetchPlatformOrgStats, getSession, listPlatformAuditLogs, exportPlatformAuditLogs,
  listPlatformConnectorPacks, listPlatformFlags, listPlatformOrgUsers,
  listPlatformOrgs, listPlatformPackages, migratePlatformEncryption, refreshSessionFlags, updatePlatformFlag,
  updatePlatformOrgDateTimeSettings, updatePlatformOrgStatus, updatePlatformOrgUser,
  type ConnectorPackDto, type FeatureFlag, type HealthDto, type OrgDateTimeSettingsDto, type PlatformHealthSummaryDto,
  type OrgMember, type PlatformAuditRow, type PlatformOrg, type PlatformPackage, type PlatformMetrics,
} from '@/lib/api';
import styles from './super-admin.module.css';

type Section='overview'|'businesses'|'onboarding'|'packages'|'access'|'health'|'audit'|'ai'|'configuration';
const NAV:{id:Section;label:string;icon:string;group:string}[]=[
 {id:'overview',label:'Command Center',icon:'⌂',group:'Platform'},
 {id:'businesses',label:'Businesses',icon:'◈',group:'Platform'},
 {id:'onboarding',label:'Register Business',icon:'+',group:'Platform'},
 {id:'packages',label:'Service Packages',icon:'▣',group:'Commercial'},
 {id:'access',label:'Access & Control',icon:'♙',group:'Control'},
 {id:'health',label:'System Health',icon:'◉',group:'Control'},
 {id:'audit',label:'Security & Audit',icon:'⌁',group:'Control'},
 {id:'ai',label:'Ellinea AI',icon:'✦',group:'Intelligence'},
 {id:'configuration',label:'System Configuration',icon:'⚙',group:'System'},
];
const roles=['owner','admin','executive','manager','member','viewer'];
const statusClass=(s:string)=>s==='active'||s==='ok'||s==='synced'?styles.statusOk:s==='suspended'||s==='error'?styles.statusBad:styles.statusNeutral;

export default function PlatformSuperAdminPage(){
 const [allowed,setAllowed]=useState<boolean|null>(null),[section,setSection]=useState<Section>('overview');
 const [orgs,setOrgs]=useState<PlatformOrg[]>([]),[packages,setPackages]=useState<PlatformPackage[]>([]),[flags,setFlags]=useState<FeatureFlag[]>([]),[packs,setPacks]=useState<ConnectorPackDto[]>([]);
 const [health,setHealth]=useState<HealthDto|null>(null),[healthSummary,setHealthSummary]=useState<PlatformHealthSummaryDto|null>(null),[audit,setAudit]=useState<PlatformAuditRow[]>([]),[auditTotal,setAuditTotal]=useState(0),[auditPage,setAuditPage]=useState(0),[selected,setSelected]=useState<PlatformOrg|null>(null);
 const [metrics,setMetrics]=useState<PlatformMetrics|null>(null);
 const [users,setUsers]=useState<OrgMember[]>([]),[stats,setStats]=useState<any>(null),[tier,setTier]=useState<any>(null),[settings,setSettings]=useState<OrgDateTimeSettingsDto>({timeFormat:'24h',dateStyle:'medium'});
 const [query,setQuery]=useState(''),[auditQuery,setAuditQuery]=useState(''),[auditOrg,setAuditOrg]=useState(''),[auditFrom,setAuditFrom]=useState(''),[auditTo,setAuditTo]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [business,setBusiness]=useState({name:'',slug:'',ownerEmail:'',ownerFullName:'',ownerPassword:''});
 const [user,setUser]=useState({email:'',fullName:'',password:'',role:'member'});
  const [pkg,setPkg]=useState({name:'',displayName:'',maxUsers:25,maxConnectors:5,requestsPerDay:10000,monthlyPrice:0,enableSso:false,enableCustomRoles:false,enableAgents:false,enableAdvancedBi:false,enableWebhooks:false});
 const [aiQ,setAiQ]=useState(''),[aiA,setAiA]=useState(''),[aiBusy,setAiBusy]=useState(false);

 const load=useCallback(async()=>{try{const[o,p,f,h,cp,m,hs]=await Promise.all([listPlatformOrgs(),listPlatformPackages(),listPlatformFlags(),fetchHealth(),listPlatformConnectorPacks(),fetchPlatformMetrics(),fetchPlatformHealthSummary()]);setOrgs(o);setPackages(p);setFlags(f);setHealth(h);setPacks(cp);setMetrics(m);setHealthSummary(hs)}catch(e){setError(e instanceof Error?e.message:'Failed to load platform data')}},[]);
  useEffect(()=>{let live=true;const decide=(s:ReturnType<typeof getSession>)=>{if(!live)return;setAllowed(Boolean(s?.isPlatformAdmin));if(s?.isPlatformAdmin)void load()};const cached=getSession();if(cached?.isPlatformAdmin){decide(cached);return()=>{live=false}}void refreshSessionFlags().then(decide).catch(()=>decide(getSession()));return()=>{live=false}},[load]);
 useEffect(()=>{if(!allowed)return;const t=setInterval(()=>{void fetchHealth().then(setHealth);void fetchPlatformMetrics().then(setMetrics);void fetchPlatformHealthSummary().then(setHealthSummary)},30000);return()=>clearInterval(t)},[allowed]);

 async function open(o:PlatformOrg){setSelected(o);setError('');try{const[s,u,p,d]=await Promise.all([fetchPlatformOrgStats(o.id),listPlatformOrgUsers(o.id),fetchPlatformOrgPackage(o.id),fetchPlatformOrgDateTimeSettings(o.id)]);setStats(s);setUsers(u);setTier(p);setSettings(d)}catch(e){setError(e instanceof Error?e.message:'Failed to load business control data')}}
 async function toggle(o:PlatformOrg){const next=o.status==='suspended'?'active':'suspended';if(!window.confirm(next==='suspended'?'Disconnect / suspend “'+o.name+'”? This blocks tenant access.':'Reconnect “'+o.name+'”?'))return;setBusy(true);try{const u=await updatePlatformOrgStatus(o.id,next);setOrgs(x=>x.map(v=>v.id===u.id?u:v));if(selected?.id===o.id)setSelected(u);setNotice(next==='suspended'?o.name+' disconnected.':o.name+' reconnected.')}catch(e){setError(e instanceof Error?e.message:'Status update failed')}finally{setBusy(false)}}
 async function register(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await createPlatformOrg({name:business.name,slug:business.slug||undefined,ownerEmail:business.ownerEmail||undefined,ownerFullName:business.ownerFullName||undefined,ownerPassword:business.ownerPassword||undefined});setNotice('Business “'+r.name+'” registered.');setBusiness({name:'',slug:'',ownerEmail:'',ownerFullName:'',ownerPassword:''});await load();setSection('businesses')}catch(e){setError(e instanceof Error?e.message:'Registration failed')}finally{setBusy(false)}}
  async function createPackage(){setBusy(true);try{await createPlatformPackage(pkg);setNotice('Package “'+pkg.displayName+'” created.');setPkg({name:'',displayName:'',maxUsers:25,maxConnectors:5,requestsPerDay:10000,monthlyPrice:0,enableSso:false,enableCustomRoles:false,enableAgents:false,enableAdvancedBi:false,enableWebhooks:false});await load()}catch(e){setError(e instanceof Error?e.message:'Package creation failed')}finally{setBusy(false)}}
 async function addUser(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);try{const u=await createPlatformOrgUser(selected.id,user);setUsers(x=>[u,...x]);setUser({email:'',fullName:'',password:'',role:'member'});setNotice('User created.')}catch(e){setError(e instanceof Error?e.message:'User creation failed')}finally{setBusy(false)}}
 async function toggleUser(u:OrgMember){if(!selected)return;setBusy(true);try{const x=await updatePlatformOrgUser(selected.id,u.id,{isActive:!u.isActive});setUsers(v=>v.map(z=>z.id===x.id?x:z))}catch(e){setError(e instanceof Error?e.message:'User update failed')}finally{setBusy(false)}}
 async function saveDate(){if(!selected)return;setBusy(true);try{await updatePlatformOrgDateTimeSettings(selected.id,settings);setNotice('Tenant settings saved.')}catch(e){setError(e instanceof Error?e.message:'Settings update failed')}finally{setBusy(false)}}
 async function loadAudit(page = auditPage){try{const r=await listPlatformAuditLogs({action:auditQuery||undefined,orgId:auditOrg||undefined,from:auditFrom||undefined,to:auditTo||undefined,limit:50,offset:page*50});setAudit(r.rows);setAuditTotal(r.total);setAuditPage(page)}catch(e){setError(e instanceof Error?e.message:'Audit load failed')}}
 async function exportAudit(){try{const blob=await exportPlatformAuditLogs({action:auditQuery||undefined,orgId:auditOrg||undefined,from:auditFrom||undefined,to:auditTo||undefined});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='eip-platform-audit.csv';a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:'Audit export failed')}} async function migrateEncryption(dryRun:boolean){setBusy(true);try{const r=await migratePlatformEncryption(dryRun,selected?.id);setNotice((dryRun?'Dry run: ':'')+'scanned '+r.scanned+', migrated '+r.migrated+', current '+r.alreadyCurrent+', failed '+r.failed+'.')}catch(e){setError(e instanceof Error?e.message:'Encryption migration failed')}finally{setBusy(false)}}
 async function askAI(e:React.FormEvent){e.preventDefault();if(!aiQ.trim())return;setAiBusy(true);try{const r=await askEllineaApi({question:aiQ,summary:null,memory:[],templateAnswer:'Use only live platform evidence; state when evidence is unavailable.',role:'platform_super_admin',organizationName:'Ellines EIP Platform'});setAiA(r.answer)}catch(e){setAiA(e instanceof Error?e.message:'AI request failed')}finally{setAiBusy(false)}}

 const shown=useMemo(()=>{const q=query.toLowerCase().trim();return q?orgs.filter(o=>[o.name,o.slug,o.status].some(v=>v.toLowerCase().includes(q))):orgs},[orgs,query]);
 const active=orgs.filter(o=>o.status==='active').length,suspended=orgs.length-active,totalUsers=orgs.reduce((n,o)=>n+o.userCount,0);
 if(allowed===null)return <main className={styles.main}>Checking platform access…</main>;
 if(!allowed)return <main className={styles.main}><div className={styles.card}><h2>Platform access denied</h2><p className={styles.cardHint}>Ellines platform operator access is required.</p></div></main>;

 const businessTable=(items:PlatformOrg[]) => <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Business</th><th>Status</th><th>Users</th><th>Created</th><th>Control</th></tr></thead><tbody>{items.map(o=><tr key={o.id}><td><strong>{o.name}</strong><br/><span className={styles.muted}>{o.slug}</span></td><td><span className={styles.status+' '+statusClass(o.status)}>{o.status}</span></td><td>{o.userCount}</td><td>{new Date(o.createdAt).toLocaleDateString()}</td><td><button className={styles.button} onClick={()=>void open(o)}>Control</button>{' '}<button className={styles.button+' '+(o.status==='active'?styles.danger:styles.success)} disabled={busy} onClick={()=>void toggle(o)}>{o.status==='active'?'Disconnect':'Reconnect'}</button></td></tr>)}{!items.length&&<tr><td colSpan={5}>No businesses found.</td></tr>}</tbody></table></div>;

 const overview=<><div className={styles.hero}><h2>Ellines EIP Control Plane</h2><p>This is the platform operating system — not a customer dashboard. Operate EIP itself, onboard businesses, assign services, troubleshoot tenants, control access, inspect security activity and configure the platform. Customer connectors are business services, not EIP infrastructure.</p><div className={styles.quick}><button className={styles.button+' '+styles.primary} onClick={()=>setSection('onboarding')}>+ Register business</button><button className={styles.button} onClick={()=>setSection('businesses')}>Manage businesses</button><button className={styles.button} onClick={()=>setSection('packages')}>Service packages</button><button className={styles.button} onClick={()=>setSection('health')}>Diagnostics</button></div></div>
 <div className={styles.grid4}><Kpi label="Businesses onboarded" value={metrics?.platform?.businesses ?? orgs.length} hint="tenant accounts"/><Kpi label="Active tenant users" value={metrics?.platform?.activeUsers ?? totalUsers} hint="currently active" cls={styles.ok}/><Kpi label="Disconnected" value={suspended} hint="access blocked" cls={suspended?styles.warn:styles.ok}/><Kpi label="API requests / 24h" value={metrics?.platform?.apiRequests24h ?? '—'} hint="real platform usage"/></div>
 <div className={styles.grid4+' '+styles.section}><Kpi label="Audit events / 24h" value={metrics?.platform?.auditEvents24h ?? '—'} hint="operator/system activity"/><Kpi label="Rate-limit violations" value={metrics?.platform?.rateLimitViolations24h ?? '—'} hint="last 24 hours" cls={metrics?.platform?.rateLimitViolations24h?styles.warn:styles.ok}/><Kpi label="Customer integrations" value={metrics?.businessServices?.connectorInstallations ?? '—'} hint="business service layer"/><Kpi label="Failed integrations" value={metrics?.businessServices?.failedConnectorInstallations ?? '—'} hint="customer troubleshooting" cls={metrics?.businessServices?.failedConnectorInstallations?styles.warn:styles.ok}/></div>
 <div className={styles.grid2+' '+styles.section}><div className={styles.card}><CardTitle title="Core EIP health" hint="System performance of EIP itself."/><div className={styles.grid2}><Service title="API" text={health?.status||'unknown'}/><Service title="Version" text={health?.version||'—'}/><Service title="Email" text={health?.email?.live?'Live · '+health.email.provider:'Not configured'}/><Service title="Feature controls" text={flags.filter(f=>f.enabled).length+'/'+flags.length+' enabled'}/></div></div><div className={styles.card}><CardTitle title="Operator attention" hint="Issues visible from current telemetry."/><Service title={suspended?suspended+' disconnected business'+(suspended===1?'':'es'):'No disconnected businesses'} text={suspended?'Review and reconnect where appropriate.':'Tenant lifecycle is clear.'}/><Service title={health?.status==='ok'?'Platform healthy':'Platform health requires attention'} text={health?.status==='ok'?'Health endpoint reports OK.':'Open diagnostics for investigation.'}/></div></div>
 <div className={styles.card+' '+styles.section}><CardTitle title="Recent businesses" hint="Fast tenant control."/><button className={styles.button} onClick={()=>setSection('businesses')}>Open all</button>{businessTable(orgs.slice(0,8))}</div></>;

 const businesses=<div className={styles.card}><CardTitle title="Business control" hint="Suspend/disconnect, inspect users, assign packages and troubleshoot every onboarded business."/><div style={{display:'flex',gap:8,marginBottom:12}}><input className={styles.input} placeholder="Search business, slug or status…" value={query} onChange={e=>setQuery(e.target.value)}/><button className={styles.button+' '+styles.primary} onClick={()=>setSection('onboarding')}>+ Register</button></div>{businessTable(shown)}</div>;

 const onboarding=<div className={styles.grid2}><form className={styles.card} onSubmit={register}><CardTitle title="Register business" hint="Create a tenant and optionally its first owner."/><div className={styles.form}><Field label="Business name" value={business.name} set={v=>setBusiness({...business,name:v})} placeholder="Acme Holdings Ltd"/><Field label="Slug" value={business.slug} set={v=>setBusiness({...business,slug:v})} placeholder="acme-holdings"/><Field label="Owner name" value={business.ownerFullName} set={v=>setBusiness({...business,ownerFullName:v})}/><Field label="Owner email" value={business.ownerEmail} set={v=>setBusiness({...business,ownerEmail:v})} type="email"/><Field label="Owner password" value={business.ownerPassword} set={v=>setBusiness({...business,ownerPassword:v})} type="password"/><div className={styles.full}><button className={styles.button+' '+styles.primary} disabled={busy||!business.name}>Register business</button></div></div></form><div className={styles.card}><CardTitle title="Onboarding sequence" hint="Keep customer-specific integrations separate from the EIP platform."/><Service title="01 · Tenant" text="Business identity, owner and lifecycle state."/><Service title="02 · Package" text="Assign the commercial capability envelope."/><Service title="03 · Integrations" text="Configure business connectors only when the customer requires them."/><Service title="04 · Verify" text="Check users, health and audit history before handoff."/></div></div>;

 const packagesPage=<><div className={styles.grid2}><div className={styles.card}><CardTitle title="Service packages" hint="Commercial capability bundles. These are not connector infrastructure."/><div className={styles.grid2}>{packages.map(p=><Service key={p.id} title={p.display_name} text={p.name+' · '+(p.monthly_price?'KES '+(p.monthly_price/100).toLocaleString()+'/month':'Custom pricing')} tags={[p.max_users?p.max_users+' users':'∞ users',p.max_connectors?p.max_connectors+' integrations':'∞ integrations',p.enable_sso?'SSO':'',p.enable_agents?'Agents':'',p.enable_advanced_bi?'Advanced BI':''].filter(Boolean)}/>)}</div></div><div className={styles.card}><CardTitle title="Create package" hint="Build a service tier for onboarding."/><div className={styles.form}><Field label="Internal name" value={pkg.name} set={v=>setPkg({...pkg,name:v})}/><Field label="Display name" value={pkg.displayName} set={v=>setPkg({...pkg,displayName:v})}/><Field label="Max users" value={String(pkg.maxUsers)} set={v=>setPkg({...pkg,maxUsers:Number(v)})} type="number"/><Field label="Max integrations" value={String(pkg.maxConnectors)} set={v=>setPkg({...pkg,maxConnectors:Number(v)})} type="number"/><Field label="Requests/day" value={String(pkg.requestsPerDay)} set={v=>setPkg({...pkg,requestsPerDay:Number(v)})} type="number"/><Field label="Monthly price (cents)" value={String(pkg.monthlyPrice)} set={v=>setPkg({...pkg,monthlyPrice:Number(v)})} type="number"/><div className={styles.full}>{(['enableSso','enableCustomRoles','enableAgents','enableAdvancedBi','enableWebhooks'] as const).map(k=><label key={k} style={{display:'block',fontSize:11,margin:'6px 0'}}><input type="checkbox" checked={pkg[k]} onChange={e=>setPkg({...pkg,[k]:e.target.checked})}/> {k.replace('enable','')}</label>)}</div><div className={styles.full}><button className={styles.button+' '+styles.primary} disabled={busy||!pkg.name||!pkg.displayName} onClick={()=>void createPackage()}>Create package</button></div></div></div></div><div className={styles.card+' '+styles.section}><CardTitle title="Business integration catalog" hint="Connector packs live here because they are customer services, not platform health dependencies."/><div className={styles.grid3}>{packs.map(p=><Service key={p.id} title={p.name} text={p.description||'Integration template'} tags={[p.catalogId,p.published?'Published':'Draft']}/>)}</div></div></>;

 const access=<div className={styles.grid2}><div className={styles.card}><CardTitle title="Tenant access" hint="Select a business to manage its users."/><select className={styles.select} value={selected?.id||''} onChange={e=>{const o=orgs.find(x=>x.id===e.target.value);if(o)void open(o)}}><option value="">Select business</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>{selected&&<form className={styles.form} style={{marginTop:12}} onSubmit={addUser}><Field label="Full name" value={user.fullName} set={v=>setUser({...user,fullName:v})}/><Field label="Email" value={user.email} set={v=>setUser({...user,email:v})}/><Field label="Password" value={user.password} set={v=>setUser({...user,password:v})} type="password"/><label className={styles.field}><span>Role</span><select className={styles.select} value={user.role} onChange={e=>setUser({...user,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><div className={styles.full}><button className={styles.button+' '+styles.primary} disabled={busy}>Add user</button></div></form>}</div><div className={styles.card}><CardTitle title={selected?selected.name:'Users'} hint={users.length+' loaded'}/>{users.map(u=><div className={styles.service} key={u.id} style={{marginBottom:8}}><strong>{u.fullName}</strong><p>{u.email} · {u.role}</p><button className={styles.button+' '+(u.isActive?styles.danger:styles.success)} onClick={()=>void toggleUser(u)}>{u.isActive?'Deactivate':'Activate'}</button></div>)}</div></div>;

 const healthPage=<><div className={styles.grid4}><Kpi label="Platform" value={healthSummary?.status||health?.status||'unknown'} hint="probed control plane" cls={healthSummary?.status==='ok'?styles.ok:styles.warn}/><Kpi label="Database" value={healthSummary?.dependencies.find(d=>d.name==='database')?.status||'unknown'} hint="live dependency probe"/><Kpi label="Email" value={healthSummary?.dependencies.find(d=>d.name==='email')?.status||'unknown'} hint={healthSummary?.dependencies.find(d=>d.name==='email')?.provider||'provider'}/><Kpi label="Checked" value={healthSummary?.checkedAt?new Date(healthSummary.checkedAt).toLocaleTimeString():'—'} hint="latest probe"/></div><div className={styles.card+' '+styles.section}><CardTitle title="Tenant diagnostics" hint="Business integration health is inspected here; it is not EIP core infrastructure."/>{businessTable(orgs)}</div></>;

 const auditPage=<div className={styles.card}><CardTitle title="Security & audit center" hint="Cross-business operator activity for investigation and accountability."/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:8,marginBottom:12}}><input className={styles.input} placeholder="Action prefix e.g. platform." value={auditQuery} onChange={e=>setAuditQuery(e.target.value)}/><select className={styles.select} value={auditOrg} onChange={e=>setAuditOrg(e.target.value)}><option value="">All businesses</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><input className={styles.input} type="date" value={auditFrom} onChange={e=>setAuditFrom(e.target.value)}/><input className={styles.input} type="date" value={auditTo} onChange={e=>setAuditTo(e.target.value)}/></div><div style={{display:'flex',gap:8,marginBottom:12,flexWrap:'wrap'}}><button className={styles.button+' '+styles.primary} onClick={()=>void loadAudit(0)}>Search</button><button className={styles.button} onClick={()=>void exportAudit()}>Export CSV</button><span className={styles.muted}>{auditTotal} matching events</span><button className={styles.button} disabled={busy} onClick={()=>void migrateEncryption(true)}>Dry-run credential migration</button><button className={styles.button+' '+styles.danger} disabled={busy} onClick={()=>{if(window.confirm('Migrate all legacy database credentials to the current master-key encryption format?'))void migrateEncryption(false)}}>Run encryption migration</button></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Time</th><th>Business</th><th>Actor</th><th>Action</th><th>Resource</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{new Date(a.createdAt).toLocaleString()}</td><td>{a.organizationName||a.organizationId}</td><td>{a.userEmail||'system'}</td><td>{a.action}</td><td>{a.resource}</td></tr>)}{!audit.length&&<tr><td colSpan={5}>No rows loaded.</td></tr>}</tbody></table></div><div style={{display:'flex',gap:8,marginTop:12}}><button className={styles.button} disabled={auditPage===0} onClick={()=>void loadAudit(auditPage-1)}>Previous</button><button className={styles.button} disabled={(auditPage+1)*50>=auditTotal} onClick={()=>void loadAudit(auditPage+1)}>Next</button></div></div>;

 const aiPage=<div className={styles.grid2}><div className={styles.card}><CardTitle title="Ellinea AI — platform operator" hint="Evidence-backed investigation and summaries; authorization remains with the operator."/><form onSubmit={askAI}><textarea className={styles.input} style={{minHeight:130,resize:'vertical'}} placeholder="Ask about platform operations or a business…" value={aiQ} onChange={e=>setAiQ(e.target.value)}/><button className={styles.button+' '+styles.primary} disabled={aiBusy||!aiQ.trim()}>{aiBusy?'Thinking…':'Ask Ellinea'}</button></form></div><div className={styles.card}><CardTitle title="AI response" hint="No answer is treated as an authorization."/><p className={styles.cardHint}>{aiA||'No response yet.'}</p></div></div>;

 const config=<div className={styles.grid2}><div className={styles.card}><CardTitle title="Global feature controls" hint="Platform-wide switches." />{flags.map(f=><div className={styles.service} key={f.key} style={{marginBottom:8}}><strong>{f.label}</strong><p>{f.note}</p><button className={styles.button+' '+(f.enabled?styles.success:'')} onClick={async()=>{try{const r=await updatePlatformFlag(f.key,!f.enabled);setFlags(r.data);setNotice(f.label+' updated.')}catch(e){setError(e instanceof Error?e.message:'Flag update failed')}}}>{f.enabled?'Enabled':'Disabled'}</button></div>)}</div><div className={styles.card}><CardTitle title="Tenant date & time" hint="Platform operator controls presentation for an onboarded business."/><select className={styles.select} value={selected?.id||''} onChange={e=>{const o=orgs.find(x=>x.id===e.target.value);if(o)void open(o)}}><option value="">Select business</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>{selected&&<div className={styles.form} style={{marginTop:12}}><label className={styles.field}><span>Time format</span><select className={styles.select} value={settings.timeFormat} onChange={e=>setSettings({...settings,timeFormat:e.target.value as '12h'|'24h'})}><option value="12h">12-hour</option><option value="24h">24-hour</option></select></label><label className={styles.field}><span>Date style</span><select className={styles.select} value={settings.dateStyle} onChange={e=>setSettings({...settings,dateStyle:e.target.value as OrgDateTimeSettingsDto['dateStyle']})}><option value="short">Short</option><option value="medium">Medium</option><option value="log">Log</option></select></label><div className={styles.full}><button className={styles.button+' '+styles.primary} onClick={()=>void saveDate()}>Save</button></div></div>}</div></div>;

 const content=section==='overview'?overview:section==='businesses'?businesses:section==='onboarding'?onboarding:section==='packages'?packagesPage:section==='access'?access:section==='health'?healthPage:section==='audit'?auditPage:section==='ai'?aiPage:config;
 const activeNav=NAV.find(n=>n.id===section)!;
 return <div className={styles.shell}><aside className={styles.rail}><div className={styles.brand}><div className={styles.brandMark}>E</div><div><h2>Ellines EIP</h2><p>Platform Control Plane</p></div></div>{['Platform','Commercial','Control','Intelligence','System'].map(g=><div className={styles.navGroup} key={g}><div className={styles.navLabel}>{g}</div>{NAV.filter(n=>n.group===g).map(n=><button key={n.id} className={styles.navBtn+' '+(section===n.id?styles.navActive:'')} onClick={()=>setSection(n.id)}><span className={styles.navIcon}>{n.icon}</span><span>{n.label}</span></button>)}</div>)}<div className={styles.railBottom}><button className={styles.navBtn} onClick={()=>window.location.href='/app'}><span className={styles.navIcon}>↩</span><span>Exit control plane</span></button></div></aside>
 <main className={styles.main}><div className={styles.topbar}><div><div className={styles.eyebrow}>Platform Super Admin · {activeNav.group}</div><h1 className={styles.title}>{activeNav.label}</h1><p className={styles.sub}>Global Ellines operations · tenant lifecycle · system control</p></div><div className={styles.topActions}><span className={styles.pill}>● {health?.status||'unknown'}</span><span className={styles.pill}>{orgs.length} businesses</span></div></div>{error&&<div className={styles.alert}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}{content}</main>
 {selected&&<><div className={styles.backdrop} onClick={()=>setSelected(null)}/><aside className={styles.drawer}><div className={styles.cardHeader}><div><div className={styles.eyebrow}>Business control</div><h2 className={styles.title} style={{fontSize:22}}>{selected.name}</h2><p className={styles.sub}>{selected.slug} · {selected.status}</p></div><button className={styles.button} onClick={()=>setSelected(null)}>Close</button></div><div className={styles.grid2}><Kpi label="Users" value={stats?.stats?.totalUsers??selected.userCount} hint="total"/><Kpi label="Integrations" value={stats?.stats?.totalConnectors??'—'} hint="customer services"/><Kpi label="Events" value={stats?.stats?.totalEvents??'—'} hint="audit/events"/><Kpi label="Pending approvals" value={stats?.stats?.pendingApprovals??'—'} hint="attention"/></div><div className={styles.card+' '+styles.section}><CardTitle title="Service package" hint="Assign the commercial capability envelope."/><select className={styles.select} value={tier?.rate_limit_tiers?.id||''} onChange={async e=>{try{await assignPlatformOrgPackage(selected.id,{tierId:e.target.value});setNotice('Package assigned.');await open(selected)}catch(err){setError(err instanceof Error?err.message:'Package assignment failed')}}}><option value="">No package</option>{packages.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></div><div className={styles.card+' '+styles.section}><CardTitle title="Tenant lifecycle" hint="Disconnect is reversible; normal control plane does not expose hard deletion."/><button className={styles.button+' '+(selected.status==='active'?styles.danger:styles.success)} onClick={()=>void toggle(selected)}>{selected.status==='active'?'Disconnect / Suspend':'Reconnect'}</button></div></aside></>}</div>;
}

function Kpi({label,value,hint,cls}:{label:string;value:string|number;hint:string;cls?:string}){return <div className={styles.kpi}><span>{label}</span><strong className={cls}>{value}</strong><small>{hint}</small></div>}
function CardTitle({title,hint}:{title:string;hint:string}){return <div className={styles.cardHeader}><div><h3 className={styles.cardTitle}>{title}</h3><p className={styles.cardHint}>{hint}</p></div></div>}
function Service({title,text,tags=[]}:{title:string;text:string;tags?:string[]}){return <div className={styles.service}><h4>{title}</h4><p>{text}</p>{tags.map(t=><span className={styles.tag} key={t}>{t}</span>)}</div>}
function Field({label,value,set,placeholder,type='text'}:{label:string;value:string;set:(v:string)=>void;placeholder?:string;type?:string}){return <label className={styles.field}><span>{label}</span><input className={styles.input} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} type={type}/></label>}
