/**
 * ConnectorCodeGeneratorService — Task 15.2 (Requirements 28.5–28.8)
 *
 * Auto-generates TypeScript connector stubs for a given system and org.
 * Generated connectors require Super Admin approval before deployment.
 */

import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Produce a safe PascalCase class name from a human-readable system name.
 */
function toClassName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9 ]/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

/**
 * Build a TypeScript connector stub string from the provided system config.
 */
function buildConnectorStub(
  systemId: string,
  systemName: string,
  config: Record<string, unknown>,
): string {
  const className = toClassName(systemName || systemId) + 'Connector';
  const endpoint = (config['endpoint'] as string | undefined) ?? 'https://api.example.com';
  const catalogId = (config['catalogId'] as string | undefined) ?? systemId;

  return `/**
 * Auto-generated connector stub for: ${systemName || systemId}
 * System ID: ${systemId}
 * Catalog ID: ${catalogId}
 *
 * ⚠️  This file was generated by Ellinea AI and requires Super Admin approval
 *     before it can be deployed to production.
 *
 * Generated at: ${new Date().toISOString()}
 */

import { Injectable } from '@nestjs/common';

export interface ${className}Config {
  endpoint: string;
  apiKey?: string;
  timeout?: number;
}

export interface SyncResult {
  success: boolean;
  recordsProcessed: number;
  errors: string[];
  syncedAt: Date;
}

@Injectable()
export class ${className} {
  private readonly endpoint: string;
  private readonly timeout: number;

  constructor(private readonly config: ${className}Config) {
    this.endpoint = config.endpoint ?? '${endpoint}';
    this.timeout = config.timeout ?? 30_000;
  }

  /**
   * Test connectivity to the external system.
   */
  async testConnection(): Promise<{ ok: boolean; latency: number }> {
    const start = Date.now();
    try {
      const res = await fetch(this.endpoint, {
        method: 'HEAD',
        signal: AbortSignal.timeout(this.timeout),
      });
      return { ok: res.ok, latency: Date.now() - start };
    } catch {
      return { ok: false, latency: Date.now() - start };
    }
  }

  /**
   * Sync data from the external system into Ellines EIP.
   * Implement the extraction, transform, and load logic here.
   */
  async sync(): Promise<SyncResult> {
    const errors: string[] = [];

    try {
      // TODO: Implement actual data extraction for ${systemName || systemId}
      // Example:
      //   const response = await fetch(\`\${this.endpoint}/data\`, { headers: { Authorization: \`Bearer \${this.config.apiKey}\` } });
      //   const data = await response.json();
      //   // transform and load data...

      return {
        success: true,
        recordsProcessed: 0,
        errors,
        syncedAt: new Date(),
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      errors.push(message);
      return {
        success: false,
        recordsProcessed: 0,
        errors,
        syncedAt: new Date(),
      };
    }
  }

  /**
   * Return the current health status of the connection.
   */
  async getHealth(): Promise<{ status: string; endpoint: string }> {
    const { ok } = await this.testConnection();
    return {
      status: ok ? 'healthy' : 'failing',
      endpoint: this.endpoint,
    };
  }
}
`;
}

// ── Service ───────────────────────────────────────────────────────────────────

@Injectable()
export class ConnectorCodeGeneratorService {
  private readonly logger = new Logger(ConnectorCodeGeneratorService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Generate a TypeScript connector stub for (systemId, orgId).
   *
   * Looks up the org's ConnectorInstallation for the given systemId to obtain
   * the system configuration.  Persists the generated code in GeneratedConnector
   * with requiresApproval semantics (approvalStatus = "pending").
   *
   * Requirement 28.5 — Connector code generation
   * Requirement 28.7 — Generated connector approval workflow
   */
  async generateConnectorCode(
    systemId: string,
    orgId: string,
    actorEmail?: string,
  ): Promise<{
    id: string;
    organizationId: string;
    systemId: string;
    systemName: string;
    language: string;
    approvalStatus: string;
    requiresApproval: true;
    isApproved: false;
    generatedAt: Date;
  }> {
    // Tenant isolation: scope installation lookup to the org
    const installation = await this.prisma.connectorInstallation.findFirst({
      where: { organizationId: orgId, catalogId: systemId },
      include: { template: true },
    });

    const systemName =
      installation?.displayName ??
      installation?.template?.name ??
      systemId;

    const config =
      (installation?.config as Record<string, unknown> | null) ?? {};

    const sourceCode = buildConnectorStub(systemId, systemName, config);

    const generated = await this.prisma.generatedConnector.create({
      data: {
        organizationId: orgId,
        systemId,
        systemName,
        sourceCode,
        language: 'typescript',
        dependencies: ['@nestjs/common', 'node-fetch'],
        testCases: [],
        approvalStatus: 'pending', // requires Super Admin approval
        generatedBy: actorEmail,
      },
    });

    this.logger.log(
      `Generated connector stub for system=${systemId} org=${orgId} generatedConnectorId=${generated.id}`,
    );

    return {
      id: generated.id,
      organizationId: generated.organizationId,
      systemId: generated.systemId,
      systemName: generated.systemName,
      language: generated.language,
      approvalStatus: generated.approvalStatus,
      requiresApproval: true,
      isApproved: false,
      generatedAt: generated.generatedAt,
    };
  }

  /**
   * Approve a generated connector (set isApproved = true via approvalStatus).
   *
   * Requirement 28.7 — Approval workflow
   * Requirement 28.8 — IT admin (Super Admin here) approval interface
   */
  async approveGeneratedConnector(
    generatedId: string,
    orgId: string,
    actorEmail: string,
  ): Promise<{
    id: string;
    organizationId: string;
    approvalStatus: string;
    isApproved: true;
    approvedAt: Date;
  }> {
    // Tenant isolation: ensure the record belongs to the org
    const existing = await this.prisma.generatedConnector.findFirst({
      where: { id: generatedId, organizationId: orgId },
    });

    if (!existing) {
      throw new NotFoundException(
        `GeneratedConnector ${generatedId} not found for org ${orgId}`,
      );
    }

    const approvedAt = new Date();

    const updated = await this.prisma.generatedConnector.update({
      where: { id: generatedId },
      data: {
        approvalStatus: 'approved',
        deployedAt: approvedAt,
      },
    });

    // Upsert the ApprovalWorkflowRequest record
    await this.prisma.approvalWorkflowRequest.upsert({
      where: { generatedConnectorId: generatedId },
      create: {
        organizationId: orgId,
        generatedConnectorId: generatedId,
        requestedBy: actorEmail,
        status: 'approved',
        approvedBy: actorEmail,
        approvedAt,
      },
      update: {
        status: 'approved',
        approvedBy: actorEmail,
        approvedAt,
      },
    });

    this.logger.log(
      `Connector ${generatedId} approved by ${actorEmail} for org=${orgId}`,
    );

    return {
      id: updated.id,
      organizationId: updated.organizationId,
      approvalStatus: updated.approvalStatus,
      isApproved: true,
      approvedAt,
    };
  }

  /**
   * List generated connectors for an org (with approval status).
   * Requirement 28.8 — Super Admin visibility into generated connectors
   */
  async listGeneratedConnectors(orgId: string) {
    return this.prisma.generatedConnector.findMany({
      where: { organizationId: orgId },
      orderBy: { generatedAt: 'desc' },
      select: {
        id: true,
        systemId: true,
        systemName: true,
        language: true,
        approvalStatus: true,
        generatedAt: true,
        generatedBy: true,
        deployedAt: true,
        // Never return sourceCode in list responses — caller must fetch by ID
      },
    });
  }

  /**
   * Get a single generated connector including its source code.
   * Only callable by Super Admin (enforced at controller level).
   */
  async getGeneratedConnector(generatedId: string, orgId: string) {
    const record = await this.prisma.generatedConnector.findFirst({
      where: { id: generatedId, organizationId: orgId },
    });

    if (!record) {
      throw new NotFoundException(
        `GeneratedConnector ${generatedId} not found`,
      );
    }

    return record;
  }
}
