/**
 * Pages Function: POST /api/v1/orgs/me/reports/:id/run
 * Mark a scheduled report as "run now" — updates lastRunAt + emails report if configured.
 * Report content is generated from the live enterprise snapshot + memory.
 */
import {
  getAdminClient,
  json,
  options,
  requireAuth,
  requireOrgAdmin,
  type Env,
} from '../../../../../../shared/auth';
import { sendOutboundEmail, resolveMailConfig } from '../../../../../../shared/mail';
import {
  deliveryFromStored,
  nextRunHintFor,
} from '../../../../../../shared/report-delivery';

type ScheduledReport = {
  id: string; title: string; cadence: string; template?: string; enabled: boolean;
  lastRunAt: string | null; nextRunHint: string; createdAt: string;
  lastEmailStatus?: string;
  recipients?: string[];
  cc?: string[];
  bcc?: string[];
  sendHour?: number | null;
};

type MemoryNote = { id: string; title: string; body: string };

function asObj(raw: unknown): Record<string, unknown> {
  if (raw && typeof raw === 'object' && !Array.isArray(raw)) {
    return raw as Record<string, unknown>;
  }
  return {};
}

function normalize(raw: unknown): ScheduledReport[] {
  if (!Array.isArray(raw)) return [];
  return (raw as ScheduledReport[]).filter(
    (x) => x && typeof x === 'object' && typeof x.id === 'string',
  ).slice(0, 40);
}

function buildReportContent(params: {
  title: string;
  orgName: string;
  runAt: string;
  healthScore: number;
  openAlerts: number;
  openDecisions: number;
  connectedSystems: number;
  briefHighlight: string;
  timeline: { title: string; detail: string }[];
  memoryNotes: MemoryNote[];
  template?: string;
}, format: 'text' | 'html' = 'text'): string {
  if (format === 'html') {
    return buildHTMLReport(params);
  }
  
  const lines: string[] = [
    `${params.title}`,
    `Organization: ${params.orgName}`,
    `Generated: ${new Date(params.runAt).toLocaleString()}`,
    `${'─'.repeat(60)}`,
    '',
    `ENTERPRISE HEALTH SUMMARY`,
    `Health Score:        ${params.healthScore}/100`,
    `Connected Systems:   ${params.connectedSystems}`,
    `Open Alerts:         ${params.openAlerts}`,
    `Open Decisions:      ${params.openDecisions}`,
    '',
    `ELLINEA AI BRIEF`,
    params.briefHighlight || 'No brief available — sync a connector to generate insights.',
    '',
  ];

  if (params.timeline.length) {
    lines.push('RECENT TIMELINE');
    for (const ev of params.timeline.slice(0, 6)) {
      lines.push(`• ${ev.title}: ${ev.detail}`);
    }
    lines.push('');
  }

  if (params.memoryNotes.length) {
    lines.push('KEY MEMORY NOTES');
    for (const note of params.memoryNotes.slice(0, 5)) {
      lines.push(`• ${note.title}: ${note.body.slice(0, 200)}`);
    }
    lines.push('');
  }

  lines.push(`${'─'.repeat(60)}`);
  lines.push(`Generated by Ellines EIP · Ellinea AI`);
  lines.push(`Powered by Ellines Tech — Where Enterprise Systems Think Together`);

  return lines.join('\n');
}

function buildHTMLReport(params: {
  title: string;
  orgName: string;
  runAt: string;
  healthScore: number;
  openAlerts: number;
  openDecisions: number;
  connectedSystems: number;
  briefHighlight: string;
  timeline: { title: string; detail: string }[];
  memoryNotes: MemoryNote[];
  template?: string;
}): string {
  const templateTitle = params.template === 'executive' ? 'Executive Report'
    : params.template === 'operational' ? 'Operational Report'
    : params.template === 'department' ? 'Department Report'
    : 'Custom Report';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${params.title}</title>
  <style>
    @page { size: A4; margin: 2cm; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.6;
      color: #0f172a;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      border-bottom: 3px solid #6F2D8D;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .logo-area {
      display: flex;
      align-items: center;
      gap: 15px;
      margin-bottom: 10px;
    }
    .logo {
      width: 48px;
      height: 48px;
      background: linear-gradient(135deg, #6F2D8D 0%, #2563EB 100%);
      border-radius: 8px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-weight: bold;
      font-size: 20px;
    }
    .brand {
      flex: 1;
    }
    .brand-name {
      font-size: 18px;
      font-weight: 600;
      color: #6F2D8D;
      margin: 0;
    }
    .tagline {
      font-size: 12px;
      color: #64748b;
      margin: 2px 0 0 0;
    }
    h1 {
      font-size: 28px;
      font-weight: 700;
      color: #0f172a;
      margin: 15px 0 5px 0;
    }
    .report-meta {
      font-size: 14px;
      color: #64748b;
      margin: 5px 0;
    }
    .template-badge {
      display: inline-block;
      background: #ede9fe;
      color: #6F2D8D;
      padding: 4px 12px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 600;
      margin-top: 8px;
    }
    .section {
      margin: 30px 0;
      page-break-inside: avoid;
    }
    .section-title {
      font-size: 18px;
      font-weight: 600;
      color: #6F2D8D;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 2px solid #e2e8f0;
    }
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 20px;
      margin: 20px 0;
    }
    .kpi-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 16px;
    }
    .kpi-label {
      font-size: 13px;
      color: #64748b;
      margin-bottom: 6px;
      font-weight: 500;
    }
    .kpi-value {
      font-size: 32px;
      font-weight: 700;
      color: #0f172a;
    }
    .health-score {
      font-size: 48px;
      color: #6F2D8D;
    }
    .brief-box {
      background: linear-gradient(135deg, #ede9fe 0%, #dbeafe 100%);
      border-left: 4px solid #6F2D8D;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
    }
    .brief-box p {
      margin: 0;
      color: #1e293b;
      line-height: 1.7;
    }
    .timeline-item, .memory-item {
      padding: 12px 0;
      border-bottom: 1px solid #e2e8f0;
    }
    .timeline-item:last-child, .memory-item:last-child {
      border-bottom: none;
    }
    .timeline-title, .memory-title {
      font-weight: 600;
      color: #0f172a;
      margin-bottom: 4px;
    }
    .timeline-detail, .memory-body {
      color: #64748b;
      font-size: 14px;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 2px solid #e2e8f0;
      text-align: center;
      color: #94a3b8;
      font-size: 13px;
    }
    .footer-brand {
      font-weight: 600;
      color: #6F2D8D;
    }
    @media print {
      body { padding: 0; }
      .section { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo-area">
      <div class="logo">E</div>
      <div class="brand">
        <p class="brand-name">Ellines EIP</p>
        <p class="tagline">Where Enterprise Systems Think Together</p>
      </div>
    </div>
    <h1>${params.title}</h1>
    <p class="report-meta"><strong>Organization:</strong> ${params.orgName}</p>
    <p class="report-meta"><strong>Generated:</strong> ${new Date(params.runAt).toLocaleString()}</p>
    <span class="template-badge">${templateTitle}</span>
  </div>

  <div class="section">
    <h2 class="section-title">Enterprise Health Summary</h2>
    <div class="kpi-grid">
      <div class="kpi-card">
        <div class="kpi-label">Health Score</div>
        <div class="kpi-value health-score">${params.healthScore}<span style="font-size: 20px; color: #64748b;">/100</span></div>
      </div>
      <div class="kpi-card">
        <div class="kpi-label">Connected Systems</div>
        <div class="kpi-value">${params.connectedSystems}</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-label">Open Alerts</div>
        <div class="kpi-value" style="color: ${params.openAlerts > 0 ? '#ef4444' : '#10b981'};">${params.openAlerts}</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-label">Open Decisions</div>
        <div class="kpi-value" style="color: ${params.openDecisions > 0 ? '#f59e0b' : '#10b981'};">${params.openDecisions}</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2 class="section-title">Ellinea AI Brief</h2>
    <div class="brief-box">
      <p>${params.briefHighlight || 'No brief available — sync a connector to generate insights.'}</p>
    </div>
  </div>

  ${params.timeline.length ? `
  <div class="section">
    <h2 class="section-title">Recent Timeline</h2>
    ${params.timeline.slice(0, 6).map(ev => `
    <div class="timeline-item">
      <div class="timeline-title">${ev.title}</div>
      <div class="timeline-detail">${ev.detail}</div>
    </div>
    `).join('')}
  </div>
  ` : ''}

  ${params.memoryNotes.length ? `
  <div class="section">
    <h2 class="section-title">Key Memory Notes</h2>
    ${params.memoryNotes.slice(0, 5).map(note => `
    <div class="memory-item">
      <div class="memory-title">${note.title}</div>
      <div class="memory-body">${note.body.slice(0, 200)}${note.body.length > 200 ? '…' : ''}</div>
    </div>
    `).join('')}
  </div>
  ` : ''}

  <div class="footer">
    <p>Generated by <span class="footer-brand">Ellines EIP</span> · Powered by Ellinea AI</p>
    <p>Ellines Tech — Where Enterprise Systems Think Together</p>
  </div>
</body>
</html>`;
}

export const onRequest: PagesFunction<Env> = async (context) => {
  if (context.request.method === 'OPTIONS') return options();
  if (context.request.method !== 'POST') {
    return json({ statusCode: 405, message: 'Method not allowed' }, 405);
  }

  const auth = await requireAuth(context.env, context.request);
  if (auth instanceof Response) return auth;

  const adminErr = requireOrgAdmin(auth.role);
  if (adminErr) return adminErr;

  const reportId = context.params.id as string;
  const supabase = getAdminClient(context.env);

  const { data: existing, error: readErr } = await supabase
    .from('organizations')
    .select('settings, name')
    .eq('id', auth.organizationId)
    .maybeSingle();
  if (readErr) return json({ statusCode: 500, message: readErr.message }, 500);

  const settings = asObj(existing?.settings);
  const orgName = (existing as { name?: string })?.name || 'Your Organization';
  const reports = normalize(settings.workflowReports);
  const idx = reports.findIndex((r) => r.id === reportId);
  if (idx === -1) return json({ statusCode: 404, message: 'Report not found' }, 404);

  const report = reports[idx];
  const now = new Date().toISOString();

  // Check for format query param (text or html for PDF printing)
  const url = new URL(context.request.url);
  const format = url.searchParams.get('format') === 'html' ? 'html' : 'text';

  // Build report content from snapshot + memory
  const snapshot = asObj(settings.enterpriseSnapshot || {});
  const memoryRaw = settings.ellineaMemory;
  const memoryNotes: MemoryNote[] = Array.isArray(memoryRaw)
    ? (memoryRaw as MemoryNote[]).filter((n) => n && typeof n.id === 'string').slice(0, 10)
    : [];

  const reportBody = buildReportContent({
    title: report.title,
    orgName,
    runAt: now,
    healthScore: typeof snapshot.healthScore === 'number' ? snapshot.healthScore : 0,
    openAlerts: typeof snapshot.openAlerts === 'number' ? snapshot.openAlerts : 0,
    openDecisions: typeof snapshot.openDecisions === 'number' ? snapshot.openDecisions : 0,
    connectedSystems: typeof snapshot.connectedSystems === 'number' ? snapshot.connectedSystems : 0,
    briefHighlight: typeof snapshot.briefHighlight === 'string' ? snapshot.briefHighlight : '',
    timeline: Array.isArray(snapshot.timeline) ? (snapshot.timeline as { title: string; detail: string }[]).slice(0, 6) : [],
    memoryNotes,
    template: report.template,
  }, format);

  // Attempt multi-recipient email delivery (To / Cc / Bcc)
  const delivery = deliveryFromStored(report);
  const toList = delivery.recipients.length
    ? delivery.recipients
    : auth.email
      ? [auth.email]
      : [];
  let emailStatus = 'not_configured';
  const mailConfig = resolveMailConfig(context.env);
  if (!toList.length) {
    emailStatus = 'failed: no recipients';
  } else if (mailConfig) {
    const emailResult = await sendOutboundEmail(context.env, {
      to: toList,
      cc: delivery.cc,
      bcc: delivery.bcc,
      subject: `${report.title} — ${orgName} (${new Date(now).toLocaleDateString()})`,
      text: reportBody,
    }).catch((err) => ({
      ok: false,
      error: err instanceof Error ? err.message : 'Send failed',
      provider: 'none' as const,
      id: undefined,
    }));
    emailStatus = emailResult.ok
      ? `delivered_via_${emailResult.provider}`
      : `failed: ${emailResult.error}`;
  }

  const updated: ScheduledReport = {
    ...report,
    recipients: delivery.recipients,
    cc: delivery.cc,
    bcc: delivery.bcc,
    sendHour: delivery.sendHour,
    lastRunAt: now,
    lastEmailStatus: emailStatus,
    nextRunHint: nextRunHintFor(report.cadence, report.enabled, delivery.sendHour),
  };

  const next = reports.map((r, i) => (i === idx ? updated : r));
  
  // Save to report history
  const historyEntry = {
    id: `run_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`,
    reportId: report.id,
    reportTitle: report.title,
    reportTemplate: report.template || 'custom',
    runAt: now,
    status: emailStatus.startsWith('delivered') ? 'sent' : emailStatus === 'not_configured' ? 'queued' : 'failed',
    emailStatus,
    recipientCount: toList.length + delivery.cc.length + delivery.bcc.length,
    reportBody,
    htmlBody: format === 'html' ? reportBody : undefined,
    reportChars: reportBody.length,
  };
  
  const existingHistory = Array.isArray(settings.reportHistory)
    ? (settings.reportHistory as typeof historyEntry[])
    : [];
  const newHistory = [historyEntry, ...existingHistory].slice(0, 200); // Keep last 200 runs
  
  const nextSettings = { ...settings, workflowReports: next, reportHistory: newHistory };

  const { error: writeErr } = await supabase
    .from('organizations')
    .update({ settings: nextSettings, updated_at: now })
    .eq('id', auth.organizationId);
  if (writeErr) return json({ statusCode: 500, message: writeErr.message }, 500);

  await supabase.from('audit_logs').insert({
    organization_id: auth.organizationId,
    user_id: auth.sub,
    action: 'workflow.report_run',
    resource: 'scheduled_report',
    metadata: {
      id: reportId,
      title: updated.title,
      emailStatus,
      toCount: toList.length,
      ccCount: delivery.cc.length,
      bccCount: delivery.bcc.length,
    },
  });

  return json({
    ...updated,
    emailStatus,
    reportChars: reportBody.length,
    deliveredTo: toList,
    deliveredCc: delivery.cc,
    deliveredBccCount: delivery.bcc.length,
  });
};
