/**
 * Pages Function: POST /api/v1/orgs/me/reports/:id/run
 * Mark a scheduled report as "run now" — updates lastRunAt + emails report if configured.
 * Report content is generated from the live enterprise snapshot + memory.
 */
import {
  getAdminClient,
  json,
  options,
  requireAuth,
  requireOrgAdmin,
  type Env,
} from '../../../../../../shared/auth';
import { sendOutboundEmail, resolveMailConfig } from '../../../../../../shared/mail';

type ScheduledReport = {
  id: string; title: string; cadence: string; enabled: boolean;
  lastRunAt: string | null; nextRunHint: string; createdAt: string;
  lastEmailStatus?: string;
};

type MemoryNote = { id: string; title: string; body: string };

function asObj(raw: unknown): Record<string, unknown> {
  if (raw && typeof raw === 'object' && !Array.isArray(raw)) {
    return raw as Record<string, unknown>;
  }
  return {};
}

function normalize(raw: unknown): ScheduledReport[] {
  if (!Array.isArray(raw)) return [];
  return (raw as ScheduledReport[]).filter(
    (x) => x && typeof x === 'object' && typeof x.id === 'string',
  ).slice(0, 40);
}

function buildReportContent(params: {
  title: string;
  orgName: string;
  runAt: string;
  healthScore: number;
  openAlerts: number;
  openDecisions: number;
  connectedSystems: number;
  briefHighlight: string;
  timeline: { title: string; detail: string }[];
  memoryNotes: MemoryNote[];
}): string {
  const lines: string[] = [
    `${params.title}`,
    `Organization: ${params.orgName}`,
    `Generated: ${new Date(params.runAt).toLocaleString()}`,
    `${'─'.repeat(60)}`,
    '',
    `ENTERPRISE HEALTH SUMMARY`,
    `Health Score:        ${params.healthScore}/100`,
    `Connected Systems:   ${params.connectedSystems}`,
    `Open Alerts:         ${params.openAlerts}`,
    `Open Decisions:      ${params.openDecisions}`,
    '',
    `ELLINEA AI BRIEF`,
    params.briefHighlight || 'No brief available — sync a connector to generate insights.',
    '',
  ];

  if (params.timeline.length) {
    lines.push('RECENT TIMELINE');
    for (const ev of params.timeline.slice(0, 6)) {
      lines.push(`• ${ev.title}: ${ev.detail}`);
    }
    lines.push('');
  }

  if (params.memoryNotes.length) {
    lines.push('KEY MEMORY NOTES');
    for (const note of params.memoryNotes.slice(0, 5)) {
      lines.push(`• ${note.title}: ${note.body.slice(0, 200)}`);
    }
    lines.push('');
  }

  lines.push(`${'─'.repeat(60)}`);
  lines.push(`Generated by Ellines EIP · Ellinea AI`);
  lines.push(`Powered by Ellines Tech — Where Enterprise Systems Think Together`);

  return lines.join('\n');
}

export const onRequest: PagesFunction<Env> = async (context) => {
  if (context.request.method === 'OPTIONS') return options();
  if (context.request.method !== 'POST') {
    return json({ statusCode: 405, message: 'Method not allowed' }, 405);
  }

  const auth = await requireAuth(context.env, context.request);
  if (auth instanceof Response) return auth;

  const adminErr = requireOrgAdmin(auth.role);
  if (adminErr) return adminErr;

  const reportId = context.params.id as string;
  const supabase = getAdminClient(context.env);

  const { data: existing, error: readErr } = await supabase
    .from('organizations')
    .select('settings, name')
    .eq('id', auth.organizationId)
    .maybeSingle();
  if (readErr) return json({ statusCode: 500, message: readErr.message }, 500);

  const settings = asObj(existing?.settings);
  const orgName = (existing as { name?: string })?.name || 'Your Organization';
  const reports = normalize(settings.workflowReports);
  const idx = reports.findIndex((r) => r.id === reportId);
  if (idx === -1) return json({ statusCode: 404, message: 'Report not found' }, 404);

  const report = reports[idx];
  const now = new Date().toISOString();

  // Build report content from snapshot + memory
  const snapshot = asObj(settings.enterpriseSnapshot || {});
  const memoryRaw = settings.ellineaMemory;
  const memoryNotes: MemoryNote[] = Array.isArray(memoryRaw)
    ? (memoryRaw as MemoryNote[]).filter((n) => n && typeof n.id === 'string').slice(0, 10)
    : [];

  const reportBody = buildReportContent({
    title: report.title,
    orgName,
    runAt: now,
    healthScore: typeof snapshot.healthScore === 'number' ? snapshot.healthScore : 0,
    openAlerts: typeof snapshot.openAlerts === 'number' ? snapshot.openAlerts : 0,
    openDecisions: typeof snapshot.openDecisions === 'number' ? snapshot.openDecisions : 0,
    connectedSystems: typeof snapshot.connectedSystems === 'number' ? snapshot.connectedSystems : 0,
    briefHighlight: typeof snapshot.briefHighlight === 'string' ? snapshot.briefHighlight : '',
    timeline: Array.isArray(snapshot.timeline) ? (snapshot.timeline as { title: string; detail: string }[]).slice(0, 6) : [],
    memoryNotes,
  });

  // Attempt email delivery
  let emailStatus = 'not_configured';
  const mailConfig = resolveMailConfig(context.env);
  if (mailConfig) {
    const emailResult = await sendOutboundEmail(context.env, {
      to: auth.email,
      subject: `${report.title} — ${orgName} (${new Date(now).toLocaleDateString()})`,
      text: reportBody,
    }).catch((err) => ({ ok: false, error: err instanceof Error ? err.message : 'Send failed', provider: 'none' as const, id: undefined }));
    emailStatus = emailResult.ok ? `delivered_via_${emailResult.provider}` : `failed: ${emailResult.error}`;
  }

  const updated: ScheduledReport = {
    ...report,
    lastRunAt: now,
    lastEmailStatus: emailStatus,
    nextRunHint: report.enabled
      ? report.cadence === 'daily' ? 'Tomorrow morning' : 'Next Monday'
      : 'Paused',
  };

  const next = reports.map((r, i) => (i === idx ? updated : r));
  const nextSettings = { ...settings, workflowReports: next };

  const { error: writeErr } = await supabase
    .from('organizations')
    .update({ settings: nextSettings, updated_at: now })
    .eq('id', auth.organizationId);
  if (writeErr) return json({ statusCode: 500, message: writeErr.message }, 500);

  await supabase.from('audit_logs').insert({
    organization_id: auth.organizationId,
    user_id: auth.sub,
    action: 'workflow.report_run',
    resource: 'scheduled_report',
    metadata: { id: reportId, title: updated.title, emailStatus },
  });

  return json({ ...updated, emailStatus, reportChars: reportBody.length });
};
